{% set name = "fastwsgi" %}
{% set version = "0.0.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fastwsgi-{{ version }}.tar.gz
  sha256: e63812196d6f3a248ba51d92df75593f94cf096d4d654d45d9921ce023ad2bf9

build:
  number: 2
  skip: true  # [py<36]
  entry_points:
    - fastwsgi = fastwsgi:run_from_cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - python
  run:
    - click >=7.0
    - python

test:
  imports:
    - fastwsgi
  commands:
    - pip check
    - fastwsgi --help
  requires:
    - pip

about:
  home: https://github.com/jamesroberts/fastwsgi
  summary: An ultra fast WSGI server for Python 3
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
