{% set name = "fastwsgi" %}
{% set version = "0.0.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fastwsgi-{{ version }}.tar.gz
  sha256: 44e6cf3952173430ea47de519b97750d49f73f729fb0c1bc61a31d8fe6d0f460

build:
  number: 0
  skip: true  # [py<36]
  entry_points:
    - fastwsgi = fastwsgi:run_from_cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
  run:
    - click >=7.0
    - python

test:
  imports:
    - fastwsgi
  commands:
    - pip check
    - fastwsgi --help
  requires:
    - pip

about:
  home: https://github.com/jamesroberts/fastwsgi
  summary: An ultra fast WSGI server for Python 3
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
